SALTO-3995: Salesforce InstalledPackage instances Change Validator (#4248)
Added a Change Validator that blocks any changes on **InstalledPackage instances**.

---

**Addition**

```
Cannot install a package using Salto
    envs/sf11/salesforce/Records/InstalledPackage/CMTD copy.nacl(line: 1)
    Error: Package with namespace TEST  cannot be installed using Salto. Please install the package directly from Salesforce's AppExchange and fetch.
```

**Removal**

```
Cannot uninstall a package using Salto
    Error: Package with namespace CMTD  cannot be uninstalled using Salto. Please uninstall this package directly from Salesforce's AppExchange and fetch.
```

**Modification**

```
InstalledPackage instances cannot be modified
    envs/sf11/salesforce/Records/InstalledPackage/CMTD.nacl(line: 1)
    Error: The InstalledPackage instance of namespace CMTD cannot be modified
```


---

_Release Notes_: 
Salesforce Adapter:
- Addition, Removal and Modification Changes of **Instances of type InstalledPackage** will be omitted with indicative error message.

---
_User Notifications_: 
_None_